version: '3'

services:
  app:
    container_name: users_backend
    build:
      context: ./go
      dockerfile: usersapi/Dockerfile
    ports: 
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - usersapi:/usr/src/app/
    depends_on:
      - live-postgres          
    networks:
      - monorepo_network

  test-service:
    container_name: test_backend
    build:
      context: ./go
      dockerfile:   testresponseapi/Dockerfile
    ports:
      - "10000:10000"
    restart: unless-stopped
    networks:
      - monorepo_network

  python-logger:
    container_name: python_logger
    build:
      context: ./Python
      dockerfile: eventslog/Dockerfile
    ports:
      - "10500:10500"
    restart: unless-stopped
    networks:
      - monorepo_network


  live-postgres:
    image: postgres:latest
    container_name: live_db_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=users_db
      - DATABASE_HOST=live-postgres
    ports:
      - "5432:5432"
    volumes:
      - database_postgres:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - monorepo_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    depends_on:
      - live-postgres
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - monorepo_network


  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
    networks:
      - monorepo_network
  nsqd:
    image: nsqio/nsq
    command:  /nsqd --broadcast-address=nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4151:4151"
      - "4150:4150"
    networks:
      - monorepo_network
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - "4171:4171"
    networks:
      - monorepo_network


volumes:
  usersapi:
  database_postgres:                  

# Networks to be created to facilitate communication between containers
networks:
  monorepo_network:
    driver: bridge
