---
db_host: live-postgres
db_driver: postgres
db_username: postgres
db_password: password
db_name: users_db
db_port: 5432

secret_key: supersecret

api_address: :8000

test_api_address: test-service:10000

events_topic: events